include: "rules/definitions.smk"
include: "rules/container.smk"
include: "rules/data.smk"
include: "rules/gridcell.smk"
include: "rules/stand.smk"
include: "rules/target.smk"


rule all:
    default_target: True
