from snakemake.utils import min_version

min_version("9.12.0")


## Common code and definitions


include: "rules/common/container.smk"
include: "rules/common/functions.smk"
include: "rules/common/wildcards.smk"
include: "rules/common/storage.smk"


## Gridcell forest variables


include: "rules/metadata/gridcell.smk"
include: "rules/data/gridcell.smk"


## Kemera and Metka declarations


include: "rules/metadata/kemera.smk"
include: "rules/data/kemera.smk"


## Forest use declaration


include: "rules/data/forest_use_declaration.smk"


## Forest stands


include: "rules/metadata/stand.smk"
include: "rules/data/stand.smk"


rule all:
    default_target: True
